import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'
import '@mantine/dates/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/components/providers'
import { Notifications } from '@mantine/notifications'
import { ColorSchemeScript } from '@mantine/core'
import MainLayout from '@/components/main-layout'
import { ClerkProvider } from '@clerk/nextjs'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  flights,
}: {
  children: ReactNode
  flights: ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <ColorSchemeScript />
          <link rel="shortcut icon" href="/favicon.svg" />
          <meta
            name="viewport"
            content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
          />
          <title></title>
        </head>
        <body>
          <Providers>
            <Notifications />
            <MainLayout>
              {children}
              {flights}
            </MainLayout>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
